apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subscriber
  name: subscriber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      annotations:
        dapr.io/app-id: subscriber
        dapr.io/enabled: 'true'
        dapr.io/app-port: '3000'
      labels:
        app: subscriber
    spec:
      containers:
      - args:
        - run
        - code/sub.go
        command:
        - go
        env:
        - name: DAPR_PUBSUB_NAME
          value: messages
        - name: APP_PORT
          value: "3000"
        image: examples/code-image:latest
        name: subscriber
        # Minikube will pull locally
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
