apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messages
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://username:password@rabbitmq.default.svc.cluster.local:5672"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: deliveryMode
    value: "0"
  - name: requeueInFailure
    value: "true"
  - name: prefetchCount
    value: "1"
  - name: reconnectWait
    value: "0"
  - name: concurrencyMode
    value: parallel